name: GitHub Action for Android Lint

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Android Lint
        uses: yutailang0119/action-android-lint@v4.0.0
        with:
          report-path: 'app/build/reports/lint-results.xml'  # Update this to the correct path in your project
          follow-symbolic-links: true  # Optional
          ignore-warnings: false       # Optional
